env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
overrides:
  - env:
      node: true
    files:
      - "*.js"
      - "*.jsx"
      - "*.ts"
      - "*.tsx"
    parserOptions:
      sourceType:
        - "script"
      project:
        - "./tsconfig.json"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
rules: { 
    'react/react-in-jsx-scope': 0,
    'react/jsx-uses-react': 0,
    '@typescript-eslint/no-floating-promises': 'off',
    '@typescript-eslint/strict-boolean-expressions': 'off'
}
